# Generated by Django 3.2.3 on 2021-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
