# Generated by Django 3.2.3 on 2021-05-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproductsmodel',
            name='product_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpropertymodel', verbose_name='ProductProperty'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.recipientmodel'),
        ),
    ]
